# Generated by Django 5.1.7 on 2025-03-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sale', to='branche.branche')),
            ],
        ),
    ]
