# Generated by Django 5.0.13 on 2025-04-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tbvendasdashboard",
            fields=[
                (
                    "idvendas",
                    models.AutoField(
                        db_column="idVendas", primary_key=True, serialize=False
                    ),
                ),
                ("nrcnpj", models.CharField(db_column="nrCNPJ", max_length=14)),
                ("nmfilial", models.CharField(db_column="nmFilial", max_length=50)),
                ("dtvenda", models.CharField(db_column="dtVenda", max_length=10)),
                (
                    "vlvenda",
                    models.DecimalField(
                        blank=True,
                        db_column="vlVenda",
                        decimal_places=2,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "txmeta",
                    models.DecimalField(
                        db_column="txMeta", decimal_places=2, max_digits=4
                    ),
                ),
            ],
            options={
                "db_table": "tbVendasDashboard",
                "managed": False,
            },
        ),
    ]
