# Generated by Django 5.1.7 on 2025-03-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('url_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cnpj', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
