# Generated by Django 5.1.7 on 2025-03-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branche', '0001_initial'),
        ('employee', '0001_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entreprise',
            new_name='Enterprise',
        ),
    ]
